//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrvatski_film
    {
        public int Film_ID { get; set; }
        public string Englesko_ime { get; set; }
    }
}
