//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nagrada
    {
        public int Nagrada_ID { get; set; }
        public Nullable<int> Film_ID { get; set; }
        public string Organizacija { get; set; }
        public string Kategorija { get; set; }
        public Nullable<int> Godina_dodjele { get; set; }
    }
}
