//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Čovjek
    {
        public int Čovjek_ID { get; set; }
        public string Ime_i_prezime { get; set; }
        public string Rod { get; set; }
        public Nullable<int> Godina_rođenja { get; set; }
        public string Država_rođenja { get; set; }
    }
}
